/**
 * Utilities for loading and retrieving assets.
 */
export class Assets {

  // Point this to a JSON file generated by TexturePacker:
  // https://www.codeandweb.com/texturepacker
  public static readonly SPRITESHEET_SRC = 'images/spritesheet.json';

  public static loader: PIXI.Loader;

  /**
   * Preloads all the Textures required by the game.
   */
  public static loadTextures(loader: PIXI.Loader, callbackFn: any): void {

    // Save this loader for later, as it is needed to retrieve Textures
    Assets.loader = loader;

    // Add an error callback
    loader.onError.add((err) => console.error(err));

    // Load our Textures
    loader.add(Assets.SPRITESHEET_SRC).load(() => callbackFn());
  }

  /**
   * Retrieves a previously-loaded Texture.
   */
  static texture(filename: string): PIXI.Texture {
    return Assets.loader.resources[Assets.SPRITESHEET_SRC].textures[filename];
  }

  /**
   * Retrieves a previously-loaded Texture.
   */
  static spritesheet(): PIXI.Spritesheet {
    return Assets.loader.resources[Assets.SPRITESHEET_SRC].spritesheet;
  }

}
